### ISSUE TITLE
The /lookup command does not display output in DMs

### ISSUE THREAD

**Issue by beaurancourt** [pgaurons/GURPS-Discord-Bot#20]
The bot's lookup command works fine in other contexts and for other commands, but only displays the summary in DMs.

Some screenshots:

DMs:
<img width="606" alt="image" src="https://user-images.githubusercontent.com/1045160/183768708-21da5d58-33cd-4952-acec-0aa10ac7999c.png">

Non DMs:
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/1045160/183768813-f6ad7120-0bf0-477f-b9ee-64fc8249f16d.png">

**Comment by pgaurons** [comment]
Fix is merged to next release.
